language: java
cache:                                                                          
  directories:                                                                  
    - $HOME/.m2
script: mvn install -DskipTests=true
